apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-jobscheduler
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: aks-jobscheduler-secret
  annotations: 
    kubernetes.io/service-account.name: aks-jobscheduler
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: jobs-manager
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-manager-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-manager
subjects:
- kind: ServiceAccount
  name: aks-jobscheduler
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobscheduler-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobscheduler
  template:
    metadata:
      labels:
        app: jobscheduler
        tier: web
    spec:
      serviceAccountName: aks-jobscheduler
      containers:
      - name: jobscheduler-web
        image: fbeltrao/aksjobscheduler-server:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: STORAGEKEY
            value: "<storage key>"
          - name: STORAGEACCOUNT
            value: "<storage account name>"
          - name: EVENTGRIDSASKEY
            value: "<optional event grid sas key to notify when job is done>"
          - name: EVENTGRIDENDPOINT
            value: "<optional event grid endpoint to notify when job is done>"
---
kind: Service
apiVersion: v1
metadata:
  name: jobscheduler-web-svc
spec:
  selector:
    app: jobscheduler
    tier: web
  ports:
  - protocol: TCP    
    port: 80
    targetPort: 8000
  type: LoadBalancer